{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Sales Data\",\"Calendar Table\",\"Measure Table\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.121.762.0 (23.09)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Entities": {
              "measure_table.total_sales": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Measure Table",
                    "ConceptualProperty": "Total Sales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Total Sales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "measure_table.total_sales_matrix_1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Measure Table",
                    "ConceptualProperty": "Total Sales Matrix 1"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Total Sales": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "868e6540-c101-48d1-867a-39038d912873",
        "fromColumn": "Order DateTime",
        "fromTable": "Sales Data",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c335b907-e699-40a8-b488-4d23b8002966"
      },
      {
        "name": "7cdb05aa-0c00-46fd-9b6e-b917bdd7bc78",
        "fromColumn": "Date",
        "fromTable": "Calendar Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_bfcf89b3-ec6a-4c90-931d-38165d545bce"
      },
      {
        "name": "3dc2f62d-d69f-474e-a46c-20d27eef5993",
        "fromColumn": "Start of Year",
        "fromTable": "Calendar Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d3e34d35-5ac9-4114-bda0-462dd219123c"
      },
      {
        "name": "5bdde2b7-bb43-453f-b3a5-ff36ab7dadc2",
        "fromColumn": "Start of Month",
        "fromTable": "Calendar Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f601c11f-3264-42c1-aa69-471df5dd90a9"
      },
      {
        "name": "25de1971-5e27-4633-ac50-59b5e53c9c3c",
        "fromColumn": "Start of Quarter",
        "fromTable": "Calendar Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a9934b7f-9a78-4e76-a3de-0b1a179c1764"
      },
      {
        "name": "73e401d2-a385-4210-9f43-8ec08a887400",
        "fromColumn": "Start of Week",
        "fromTable": "Calendar Table",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_18897a75-fff4-44a3-9626-02c0af51bcb6"
      },
      {
        "name": "9807940a-95fe-4454-88a5-605df18acfed",
        "fromColumn": "OrderDate",
        "fromTable": "Sales Data",
        "toColumn": "Date",
        "toTable": "Calendar Table"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Sales Data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ff1943d-d099-4761-9b04-53bb8db62b20",
            "sourceColumn": "Index",
            "summarizeBy": "sum"
          },
          {
            "name": "Order ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ba39bdfa-e0c8-455e-ba25-8b524571f803",
            "sourceColumn": "Order ID",
            "summarizeBy": "count"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9880ad32-18a2-424c-94c7-5b803ca88aca",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity Ordered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "26c17d13-3127-47b8-b427-ffc153b335d2",
            "sourceColumn": "Quantity Ordered",
            "summarizeBy": "sum"
          },
          {
            "name": "Price Each",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"₹\"\\ #,0.###############;#,0.###############\\ -\"₹\";\"₹\"\\ #,0.###############",
            "lineageTag": "1dc2ec54-0ca2-4063-bd68-d1b4353abc2f",
            "sourceColumn": "Price Each",
            "summarizeBy": "sum"
          },
          {
            "name": "Order DateTime",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "9e5c8cd6-245e-4ef4-93ce-05099e5f2294",
            "sourceColumn": "Order DateTime",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_c335b907-e699-40a8-b488-4d23b8002966"
                },
                "isDefault": true,
                "relationship": "868e6540-c101-48d1-867a-39038d912873"
              }
            ]
          },
          {
            "name": "OrderDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e057da7f-495b-4267-910f-2e21d6c4b306",
            "sourceColumn": "OrderDate",
            "summarizeBy": "none"
          },
          {
            "name": "Purchase Address",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "Address",
            "dataType": "string",
            "lineageTag": "1aaa146a-53b5-4b0f-a686-c4ac7d0953bc",
            "sourceColumn": "Purchase Address",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8c9a5684-2297-46a4-b443-6452527dbbef",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"₹\"\\ #,0.###############;#,0.###############\\ -\"₹\";\"₹\"\\ #,0.###############",
            "lineageTag": "95239cbc-7545-4e34-87f9-5621a6e9df65",
            "sourceColumn": "Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "City",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataCategory": "City",
            "dataType": "string",
            "lineageTag": "6bfc7b5e-9f2b-450b-b65f-26a5ba27fedf",
            "sourceColumn": "City",
            "summarizeBy": "none"
          },
          {
            "name": "Hour",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8e062efb-8a44-4c2d-bb34-f0af886579c9",
            "sourceColumn": "Hour",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "1d3c6941-8cf1-4d36-8a77-639a89f49698",
        "partitions": [
          {
            "name": "Sales Data",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Csv.Document(File.Contents(\"C:\\Users\\sarav\\OneDrive\\Desktop\\meriskill\\Dataset MeriSKILL\\Sales Data.csv\"),[Delimiter=\",\", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),",
                "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Promoted Headers\",{\"\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Order ID\", Int64.Type}, {\"Quantity Ordered\", Int64.Type}, {\"Price Each\", Currency.Type}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Order Date\", \"Order DateTime\"}}),",
                "    #\"Inserted Parsed Date\" = Table.AddColumn(#\"Renamed Columns\", \"Parse\", each Date.From(DateTimeZone.From([Order DateTime])), type date),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Inserted Parsed Date\",{{\"Parse\", \"OrderDate\"}}),",
                "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Renamed Columns1\",{\"Order ID\", \"Product\", \"Quantity Ordered\", \"Price Each\", \"Order DateTime\", \"OrderDate\", \"Purchase Address\", \"Month\", \"Sales\", \"City\", \"Hour\"}),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Reordered Columns\",{{\"Order DateTime\", type datetime}, {\"OrderDate\", type date}, {\"Month\", Int64.Type}, {\"Sales\", Currency.Type}, {\"Hour\", Int64.Type}}),",
                "    #\"Added Index\" = Table.AddIndexColumn(#\"Changed Type1\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns1\" = Table.ReorderColumns(#\"Added Index\",{\"Index\", \"Order ID\", \"Product\", \"Quantity Ordered\", \"Price Each\", \"Order DateTime\", \"OrderDate\", \"Purchase Address\", \"Month\", \"Sales\", \"City\", \"Hour\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Reordered Columns1\",{\"Index\"}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Removed Columns1\",{{\"OrderDate\", Order.Ascending}}),",
                "    #\"Added Index1\" = Table.AddIndexColumn(#\"Sorted Rows\", \"Index\", 1, 1, Int64.Type),",
                "    #\"Reordered Columns2\" = Table.ReorderColumns(#\"Added Index1\",{\"Index\", \"Order ID\", \"Product\", \"Quantity Ordered\", \"Price Each\", \"Order DateTime\", \"OrderDate\", \"Purchase Address\", \"Month\", \"Sales\", \"City\", \"Hour\"})",
                "in",
                "    #\"Reordered Columns2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_7dff1e2e-3a62-487e-b96a-9f5492ca4eed",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4fe1fe2d-51b8-4761-8f20-dc5567263f67",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b71bcbf3-461c-4e8b-b064-62faef2735bd",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "cc36441e-b7b8-40f1-aa47-8f634e4c7a8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "49c85aa1-2541-4dc5-bab6-e411e0f60bcf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "350d2002-7c84-4d3a-84c9-a9c23c9b854e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "74aaf73e-331f-4f78-99b3-5caa6cdc5efa",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "e7dd85ea-67e8-4ab9-a5db-67505d3351f2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "e95885a6-1cea-408a-ad54-4968267605b7",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8b7554e4-c8fb-46b8-bfc4-2722d789b653",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "41ac6972-f003-4877-8501-ab97c5344766",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "77f79368-83fb-4099-b31f-da77cc0e9f96",
                "ordinal": 3
              }
            ],
            "lineageTag": "30d76869-436b-4d5e-a2d3-3acf4ea3e4ab"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2fdf6ef1-3f65-4695-abbd-d9c7ee56eef3",
        "partitions": [
          {
            "name": "DateTableTemplate_7dff1e2e-3a62-487e-b96a-9f5492ca4eed",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c335b907-e699-40a8-b488-4d23b8002966",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "bd7d743e-264b-4252-8fb4-d26788e940b3",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0c4c7ec3-d92d-4082-837f-aecfa83a5a49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5792ced7-9734-4149-b7dc-13b7e3cfd606",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "06f4537e-8e2d-438c-a592-10e7dc210d1f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "82a68682-c2c6-4697-b2a6-bcd7cc024b23",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "437a5588-7286-45da-8d1e-959c7edaf977",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2c5db3f8-2da6-456c-883d-c6b65969b2c1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "136e996e-43c0-4018-aec1-92b11871fe3c",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "71617a0f-66f4-48f4-a46f-28913c63a491",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "bc301a18-38a3-4737-b646-83f85cf2eae4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "60d4bbec-c542-4140-89a0-fbc7852af398",
                "ordinal": 3
              }
            ],
            "lineageTag": "3ec85379-a43e-4e9e-910f-f26322a473ad"
          }
        ],
        "isHidden": true,
        "lineageTag": "d431b7c3-2d46-4cc9-b6a6-e1b1dab4ca82",
        "partitions": [
          {
            "name": "LocalDateTable_c335b907-e699-40a8-b488-4d23b8002966",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Sales Data'[Order DateTime])), 1, 1), Date(Year(MAX('Sales Data'[Order DateTime])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Calendar Table",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "df70c413-bc64-48b4-983a-0ba0795f532b",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_bfcf89b3-ec6a-4c90-931d-38165d545bce"
                },
                "isDefault": true,
                "relationship": "7cdb05aa-0c00-46fd-9b6e-b917bdd7bc78"
              }
            ]
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c08c214b-d311-4ad7-a6cd-9969ad0082ee",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3a6fc61a-fc9e-43e0-8e53-4fc2c34d420e",
            "sourceColumn": "Start of Year",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d3e34d35-5ac9-4114-bda0-462dd219123c"
                },
                "isDefault": true,
                "relationship": "3dc2f62d-d69f-474e-a46c-20d27eef5993"
              }
            ]
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "33d644c3-4d0d-4d57-b1f1-d5636a1fa04c",
            "sourceColumn": "Month",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a1d80c53-5299-49b8-996c-fec6cf3cd29a",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f601c11f-3264-42c1-aa69-471df5dd90a9"
                },
                "isDefault": true,
                "relationship": "5bdde2b7-bb43-453f-b3a5-ff36ab7dadc2"
              }
            ]
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c45afec3-cdf3-421a-b620-cb73292f809f",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "14b617ab-d984-4432-b083-59c99272e132",
            "sourceColumn": "Quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "Start of Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ffada12d-91a4-4b04-8987-ccedf2777f76",
            "sourceColumn": "Start of Quarter",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_a9934b7f-9a78-4e76-a3de-0b1a179c1764"
                },
                "isDefault": true,
                "relationship": "25de1971-5e27-4633-ac50-59b5e53c9c3c"
              }
            ]
          },
          {
            "name": "Start of Week",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f94fa1fc-d5ce-48da-9994-bc5cbc12cd9e",
            "sourceColumn": "Start of Week",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_18897a75-fff4-44a3-9626-02c0af51bcb6"
                },
                "isDefault": true,
                "relationship": "73e401d2-a385-4210-9f43-8ec08a887400"
              }
            ]
          },
          {
            "name": "Day Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "775c5e56-cb70-4bf9-8a23-92d1bc2bd826",
            "sourceColumn": "Day Name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ff56aa3-0bd3-43b5-89e5-a524e77945dd",
        "partitions": [
          {
            "name": "Calendar Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = List.Dates(#date(2019, 1, 1), 370 , #duration(1, 0, 0, 0)),",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type date}}),",
                "    #\"Inserted Year\" = Table.AddColumn(#\"Changed Type\", \"Year\", each Date.Year([Column1]), Int64.Type),",
                "    #\"Inserted Start of Year\" = Table.AddColumn(#\"Inserted Year\", \"Start of Year\", each Date.StartOfYear([Column1]), type date),",
                "    #\"Inserted Month\" = Table.AddColumn(#\"Inserted Start of Year\", \"Month\", each Date.Month([Column1]), Int64.Type),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Inserted Month\", \"Start of Month\", each Date.StartOfMonth([Column1]), type date),",
                "    #\"Inserted Month Name\" = Table.AddColumn(#\"Inserted Start of Month\", \"Month Name\", each Date.MonthName([Column1]), type text),",
                "    #\"Inserted Quarter\" = Table.AddColumn(#\"Inserted Month Name\", \"Quarter\", each Date.QuarterOfYear([Column1]), Int64.Type),",
                "    #\"Inserted Start of Quarter\" = Table.AddColumn(#\"Inserted Quarter\", \"Start of Quarter\", each Date.StartOfQuarter([Column1]), type date),",
                "    #\"Inserted Start of Week\" = Table.AddColumn(#\"Inserted Start of Quarter\", \"Start of Week\", each Date.StartOfWeek([Column1]), type date),",
                "    #\"Inserted Day\" = Table.AddColumn(#\"Inserted Start of Week\", \"Day\", each Date.Day([Column1]), Int64.Type),",
                "    #\"Inserted Day Name\" = Table.AddColumn(#\"Inserted Day\", \"Day Name\", each Date.DayOfWeekName([Column1]), type text),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Inserted Day Name\",{\"Day\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Column1\", \"Date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_bfcf89b3-ec6a-4c90-931d-38165d545bce",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "480653e1-b0c9-4a4d-a88f-738da5f07eed",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "124d8835-0322-414d-83b8-fd016d0eb814",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "82d125fe-a73c-40de-b94e-c73fd1746131",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "49e4ac67-041a-4991-a64a-160a046b388d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "44249a8d-f704-4c7f-b0c2-fefbebf3cc91",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5344dc83-89c4-4c0b-ae12-2de100b3705d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4705432b-2ad3-41e6-a9b4-0e46b22dc063",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "501eea7f-dd02-4010-8dbf-4bd362d57262",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "7eb61674-39cd-449a-9454-90f263327033",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "c9361530-fe8f-4ed2-aa69-db8cccb4c8d2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "27ce005e-406e-494c-be3c-7b3e04f4a96f",
                "ordinal": 3
              }
            ],
            "lineageTag": "afe731c1-e934-4f0c-822f-cc1db805aca5"
          }
        ],
        "isHidden": true,
        "lineageTag": "5e85d758-0cf2-4156-acee-fefd97e455fa",
        "partitions": [
          {
            "name": "LocalDateTable_bfcf89b3-ec6a-4c90-931d-38165d545bce",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Table'[Date])), 1, 1), Date(Year(MAX('Calendar Table'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d3e34d35-5ac9-4114-bda0-462dd219123c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c38b9a33-3784-4d6a-8410-f1aae8a04fea",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "b3ef83fd-f8b2-44ea-bd52-e22c0842fdbc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a0beb8b3-f42c-4d95-9898-4d270827e3c9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "f3c4bf3e-613f-4076-bb8d-971280cd5a19",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a21b8099-f623-46e0-af32-c9c988ac72b2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b4476ebf-06de-4536-a591-6464c29525bd",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "06c3a095-7230-44b3-9462-b615b3c105ae",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2a1423ae-5d6a-4306-8ded-d9763f6acb05",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "890877e3-3948-48a9-b8cd-5ff6dbd79f08",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3b291c22-961f-44d9-9375-c3898e948f64",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "1946e2e1-09e5-40aa-9a65-b47dd383b94d",
                "ordinal": 3
              }
            ],
            "lineageTag": "da5a5722-3aa0-4982-85b6-4881d965ee7c"
          }
        ],
        "isHidden": true,
        "lineageTag": "3a37840c-0f0a-46ab-a8ec-aad522fd3652",
        "partitions": [
          {
            "name": "LocalDateTable_d3e34d35-5ac9-4114-bda0-462dd219123c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Table'[Start of Year])), 1, 1), Date(Year(MAX('Calendar Table'[Start of Year])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f601c11f-3264-42c1-aa69-471df5dd90a9",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ed7cbadf-66d3-4bd5-81fb-df7df20a6ede",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "797dda3a-e0b5-48f5-9240-f3f0096e616f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9c63e005-1846-411d-8982-2f7eb394004e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0075c947-4f34-4b37-97a5-17fd8f430467",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7c19aeb7-1849-4e3c-8451-b3975daa8aae",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ff586dca-91f1-4f6a-9f02-ace3dc4749df",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3b4c18fb-da35-4d2d-a41b-7ab974dc5074",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "f077c275-1dda-4c7b-9582-ec388d4e7373",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c8aa947d-e066-43d7-92c4-bc598a8deba8",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6f498131-de08-433c-93b6-a6bda2c9551a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "223c7bf6-d5ad-4b38-a0b3-5a8bdf31ad7e",
                "ordinal": 3
              }
            ],
            "lineageTag": "e98be19e-9d0d-4a09-86d8-53e2fb2fd7b2"
          }
        ],
        "isHidden": true,
        "lineageTag": "665eec0d-b7e1-4762-bd19-94323c60e13f",
        "partitions": [
          {
            "name": "LocalDateTable_f601c11f-3264-42c1-aa69-471df5dd90a9",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Table'[Start of Month])), 1, 1), Date(Year(MAX('Calendar Table'[Start of Month])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a9934b7f-9a78-4e76-a3de-0b1a179c1764",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1dc89e05-b488-4d2b-9521-d723278f53c6",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "73b19492-a4e9-46d3-b386-9754a366f89d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fcb8c022-9107-459f-8268-7b081581e3a8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a4325da7-8685-46dc-8da1-6a05fafba405",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "2ce4ac26-3449-4318-bc28-7ea970d25d42",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "40120e07-9f49-41a4-a17f-8f735f6a3092",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3570a1eb-116a-410b-91e1-cb3796eb35e0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "99f89c6c-3ede-4364-a270-c1eeba124e85",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "8c53d2ba-ef07-4e55-a11e-0924914cec70",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "f628a920-4cad-4d28-9bcf-0b723efabfc0",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "282efed4-34c6-4a9d-9d9f-143aa0ce2253",
                "ordinal": 3
              }
            ],
            "lineageTag": "916d4b88-5923-4493-bd85-1ebdfc8810e7"
          }
        ],
        "isHidden": true,
        "lineageTag": "6e641044-72a1-47b2-9419-e30b8c2d2f7d",
        "partitions": [
          {
            "name": "LocalDateTable_a9934b7f-9a78-4e76-a3de-0b1a179c1764",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Table'[Start of Quarter])), 1, 1), Date(Year(MAX('Calendar Table'[Start of Quarter])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_18897a75-fff4-44a3-9626-02c0af51bcb6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "85b8f23f-f6a9-4a1f-a96a-89704e847a8f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "7cd83eb4-17e7-4380-b1bb-fb194cf947c2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "42ffbf37-fde6-4cb3-ae49-6702cdb7c092",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "416395ba-0f17-4b85-9e06-4e352cca75f2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "f02f4ed4-fa8d-4282-9a23-0ff19b33ad64",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "511bfceb-2c14-4b52-873e-68c2351dd4f3",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fa27e55a-2efc-480e-a612-31ac60344c84",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "2964d5ee-4a00-456d-8042-9035c33fc427",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c0a0a92e-7a5a-4efd-9681-6e4467b12068",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "6fd4fec9-1f0e-4286-8ddc-f22159722899",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "02751ed6-196e-41c5-94fd-20f025bc6613",
                "ordinal": 3
              }
            ],
            "lineageTag": "70da265e-5cbd-424a-abaa-4a4704bab8ca"
          }
        ],
        "isHidden": true,
        "lineageTag": "a5c8591b-a485-4184-8794-65f34f54945e",
        "partitions": [
          {
            "name": "LocalDateTable_18897a75-fff4-44a3-9626-02c0af51bcb6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Calendar Table'[Start of Week])), 1, 1), Date(Year(MAX('Calendar Table'[Start of Week])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "Measure Table",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "e19f5a5b-6799-43b6-8562-ffd3cd4225dd",
        "measures": [
          {
            "name": "Total Orders",
            "expression": "DISTINCTCOUNT('Sales Data'[Order ID])",
            "formatString": "0",
            "lineageTag": "41332fa3-ce3b-4fa5-8b3b-9b21e3ad7dbf"
          },
          {
            "name": "Total Sales Card",
            "expression": "FORMAT(ROUND(SUM('Sales Data'[Sales]),2),\"#$,##0,,.0M\")",
            "lineageTag": "7f7384ec-d29e-434f-881a-fb5bafa4b843"
          },
          {
            "name": "Total Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "expression": "SUM('Sales Data'[Sales])",
            "formatString": "\"₹\"\\ #,0.00;#,0.00\\ -\"₹\";\"₹\"\\ #,0.00",
            "lineageTag": "dbac2610-a8d5-4c33-afd5-392fe77db786"
          },
          {
            "name": "Total Sales Matrix 1",
            "expression": "FORMAT(ROUND(SUM('Sales Data'[Sales]),2),\"#$,##0,,.00M\")",
            "lineageTag": "8612d847-e126-4ca2-b080-fcdae9d80806"
          },
          {
            "name": "Previous Month Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "expression": "CALCULATE([Total Sales],DATEADD('Calendar Table'[Date],-1,MONTH))",
            "formatString": "\"₹\"\\ #,0.###############;#,0.###############\\ -\"₹\";\"₹\"\\ #,0.###############",
            "lineageTag": "bdcbb558-4cb2-4409-8963-5eed5aebe63e"
          },
          {
            "name": "Prev Month Orders",
            "expression": "CALCULATE([Total Orders],DATEADD('Calendar Table'[Date],-1,MONTH))",
            "formatString": "0",
            "lineageTag": "ec8904da-074c-40c5-8fa1-af2481489325"
          },
          {
            "name": "Adjusted Sales",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "expression": "[Total Sales]*(1+'Price Adjustment Percentage'[Price Adjustment Percentage Value])",
            "formatString": "\"₹\"\\ #,0.###############;#,0.###############\\ -\"₹\";\"₹\"\\ #,0.###############",
            "lineageTag": "60577c31-4f51-427e-a7b8-cf0e9ea83abb"
          },
          {
            "name": "Peak Hour",
            "expression": "\"19:00\"",
            "lineageTag": "be7a3196-333d-4a1e-96b8-52e451fb69a8"
          },
          {
            "name": "Adjusted Sales1",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-IN\"}"
              }
            ],
            "expression": "SUMX('Sales Data',('Sales Data'[Price Each]*(1+'Price Adjustment Percentage'[Price Adjustment Percentage Value])*'Sales Data'[Quantity Ordered]))",
            "formatString": "\"₹\"\\ #,0.###############;#,0.###############\\ -\"₹\";\"₹\"\\ #,0.###############",
            "lineageTag": "d873602e-2c28-4230-ae22-58afc13ec06f"
          }
        ],
        "partitions": [
          {
            "name": "Measure Table",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "total orders and sales",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "57ee1ff5afda478fbaba10110af87841"
          }
        ],
        "columns": [
          {
            "name": "total orders and sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "a87eadfd-9287-4b28-8315-72c6122f0d1d",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "total orders and sales Fields"
                }
              ]
            },
            "sortByColumn": "total orders and sales Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "total orders and sales Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "b57e9245-f7a7-4af8-aef5-207bb58f9537",
            "sortByColumn": "total orders and sales Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "total orders and sales Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "02fc1c8a-c00a-4d1e-9020-ff5bd1db5698",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "192cbe49-4093-4bd5-a016-63ba14ca0fab",
        "partitions": [
          {
            "name": "total orders and sales",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Total Orders\", NAMEOF('Measure Table'[Total Orders]), 0),",
                "    (\"Total Sales\", NAMEOF('Measure Table'[Total Sales]), 1)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Price Adjustment Percentage",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c4110da672e1403cbd963b957e6a55ca"
          }
        ],
        "columns": [
          {
            "name": "Price Adjustment Percentage",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "version": 0
                }
              }
            ],
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "86b89f32-4a6e-4b5c-bd71-acadc8875fe8",
            "sourceColumn": "[Value]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "71d0087b-7176-4806-872b-62805aba04b3",
        "measures": [
          {
            "name": "Price Adjustment Percentage Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "SELECTEDVALUE('Price Adjustment Percentage'[Price Adjustment Percentage], 0)",
            "lineageTag": "5c90bf40-8b94-4be5-96fe-1be8929a6c20"
          }
        ],
        "partitions": [
          {
            "name": "Price Adjustment Percentage",
            "mode": "import",
            "source": {
              "expression": "GENERATESERIES(-1, 1, 0.1)",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}